### ISSUE TITLE
Ticket attachments for attendee emails are not working.

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-server#6155]
**Describe the bug**
After adding support for multi attendee ticket downloads, the storage path was changed. Due to this, the tickets weren't being attached. Ergo, the email wasn't being sent. 

**Reference**
The key was changed in this PR. https://github.com/fossasia/open-event-server/pull/6095
**To Reproduce**
1. Place any order
2. Email is not sent

**Expected behavior**
 Emails & attachments should work as expected.
**Stacktrace**
```
/open-event-server/app/api/helpers/tasks.py", line 64, in send_email_task_sendgrid
    with open(attachment, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'generated/tickets/attendees/tickets/pdf/4c0b138f-fd0c-489b-a30b-57c971014861/dDlYVnIrN1/4c0b138f-fd0c-489b-a30b-57c971014861.pdf'
```

**Comment by mrsaicharan1** [comment]
@uds5501 @shreyanshdwivedi @iamareebjamal This should fix the email `FileNotFoundError`

**Comment by iamareebjamal** [comment]
Still not working

`No such file or directory: 'generated/tickets/orders/tickets/pdf/9b2314a4-594b-485d-9997-f5ca4a716f12/UC9XeTI5Q3/9b2314a4-594b-485d-9997-f5ca4a716f12.pdf'`

**Comment by mrsaicharan1** [comment]
@iamareebjamal This issue was regarding the attachments. When the email was successfully sent, the tickets are attached. Why was this re-opened?

**Comment by iamareebjamal** [comment]
Because it's still not fixed?

**Comment by mariobehling** [comment]
We are not sending the tickets anymore. Therefore closing the issue.
